### PR TITLE
Add GitHub Action to run the tests

### LINKED ISSUE #271: Setup a GitHub Action to run the tests

### PR DESCRIPTION
**Pull request by abdonrd**
## Changes

Fix #271

### CODE REVIEW

**Comment by abdonrd** [comment]
Looks like when we run the `npm test` it already run the tests inside the `md-renderer`.

So... Remove the `Test (md-renderer)` job or update the `npm test` to just run the app tests?
@Qiskit/qiskit-digital-devs what do you think?

**Comment by Tansito** [comment]
I would have both honestly:
- `npm test`: run all the tests
- `npm test:nuxt`: run the tests from nuxt
- `npm test:md-renderer`: run the tests from renderer

**Comment by abdonrd** [comment]
I have created a new issue to not block this PR:

- https://github.com/Qiskit/saiba/issues/285

**Review by Tansito — APPROVED** [review]
Let's divide the tests later then! 💯

**Pull request merged**
