### PR TITLE
Fix MathJax fonts path

### PR DESCRIPTION
**Pull request by abdonrd**
## Changes

Fix MathJax fonts path using the Nuxt's aliases:
https://nuxt.com/docs/api/configuration/nuxt-config/#alias

With this, we didn't fix the #4 issue completely, but we fix a part of it.

Explanation here: https://github.com/Qiskit/saiba/issues/4#issuecomment-1369852201

Before:
Screenshot 2023-01-03 at 3 18 51 PM

Screenshot 2023-01-03 at 9 55 29 AM

After:
Screenshot 2023-01-03 at 3 19 09 PM

Screenshot 2023-01-03 at 9 55 45 AM

### CODE REVIEW

**Review by techtolentino — COMMENTED** [review]
@abdonrd - not sure if I'm doing something wrong here 🤔 

I'm seeing an error in my build that I don't see in your screenshot.

Any ideas?

Screenshot 2023-01-03 at 10 21 02 AM

**Comment by abdonrd** [comment]
Looks like an error with the Plex font...
Did you update the dependencies?

**Review by techtolentino — APPROVED** [review]
Reinstalled dependencies, and after discussing w/ Abdon in Slack, I think this is good 👍🏼

**Review by yoshiemuranaka — COMMENTED** [review]
Hmm strange..I'm still seeing errors in the browser console with these changes..

**Comment by abdonrd** [comment]
> Hmm strange..I'm still seeing errors in the browser console with these changes..

But the errors you see are from Mathjax library, right?
Not from the `assets/scss/mathjax-fonts.scss`

**Comment by yoshiemuranaka** [comment]
> But the errors you seeing are from Mathjax library, right? Not from the `assets/scss/mathjax-fonts.scss`

Yes! is that expected? (not resolved error)

Screenshot 2023-01-03 at 11 11 56 AM

**Comment by abdonrd** [comment]
Yes, it's expected!

This PR only fix the paths from the `assets/scss/mathjax-fonts.scss`.

**Comment by yoshiemuranaka** [comment]
> Yes, it's expected!
> 
> This PR only fix the paths from the `assets/scss/mathjax-fonts.scss`.

Ok thanks! I'm trying to see what exactly is fixed. I'm still seeing the `Before` errors in the browser console. I'm not seeing any of build related warnings in the terminal (before or after)

I'm ok to merge this! Just wasn't sure what to check

**Review by yoshiemuranaka — APPROVED** [review]
lgtm–seeing that the console warnings are no longer there with this change

**Pull request merged**
