### PR TITLE
feature(utility panel): Add glossary & render math

### PR DESCRIPTION
**Pull request by frankharkins**
## Changes

Works towards https://github.com/Qiskit/saiba/issues/373

- Adds `assets/content/universal-notation.json` which contains the content for the glossary.
  
  This is from [platypus](https://github.com/Qiskit/platypus/blob/main/notebooks/shared/universal-notations.yaml) (converted to json and stripped of `$`). I've converted to JSON to get an MVP; I think this should move to the database and be yaml, but I can't work out how to import yaml correctly.
- Uses the `RendererMath` component to render the symbols

### CODE REVIEW

**Review by techtolentino — APPROVED** [review]
Great to see this working @frankharkins - nicely done.

I'm good w/ this!

**Review by abdonrd — APPROVED** [review]
Looks good as a first step, thanks Frank!

**Comment by abdonrd** [comment]
Regarding the database, we already have a `Notations` collection type for this. The scheme is:

Screenshot 2022-12-15 at 12 27 46 AM

**Review by Tansito — APPROVED** [review]
Thanks for this @frankharkins 🚀  . 

As first step I see it more than enough. I agree with @abdonrd  that maybe as next step we can decide if we are going to store this information in database or we just have it statically as @techtolentino suggested.

**Pull request merged**
